ktor {
    deployment {
        port = ${?PORT} # uses PORT sys env if defined, otherwise use 8080
        port = 8080
        host = "0.0.0.0"
    }

    application {
        modules = [ com.flightbooking.ApplicationKt.module ]
    }
}